services:
  garagebid-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: garagebid
      POSTGRES_USER: garagebid
      POSTGRES_PASSWORD: garagebid
    ports:
      - "5432:5432"
    volumes:
      - garagebid-db-data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d

volumes:
  garagebid-db-data: