services:

  catalog-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: catalog
      POSTGRES_USER: garagebid
      POSTGRES_PASSWORD: garagebid
    ports:
      - "5433:5432"
    volumes:
      - catalog-db-data:/var/lib/postgresql/data

  auction-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: auction
      POSTGRES_USER: garagebid
      POSTGRES_PASSWORD: garagebid
    ports:
      - "5434:5432"
    volumes:
      - auction-db-data:/var/lib/postgresql/data

  consul:
    image: hashicorp/consul:2.0.2
    command: agent -dev -client=0.0.0.0 -ui
    ports:
      - "8500:8500"
      - "8600:8600/udp"

volumes:
  catalog-db-data:
  auction-db-data: