server:
  port: 8082

spring:
  application:
    name: auction

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
        ip-address: 127.0.0.1
        instance-id: ${spring.application.name}-${server.port}
        health-check-url: http://host.docker.internal:${server.port}/actuator/health
        query-passing: true

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5434/auction}
    username: ${DB_USERNAME:garagebid}
    password: ${DB_PASSWORD:garagebid}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

  mvc:
    problemdetails:
      enabled: true

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        enable.idempotence: true

garagebid:
  outbox:
    topic: garagebid.auction.events
    batch-size: 10
    poll-delay-ms: 1000
    lease-duration: 60s
    send-timeout: 5s

management:
  endpoints:
    web:
      exposure:
        include: health,info