server:
  port: 8082

spring:
  application:
    name: auction
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/garagebid}
    username: ${DB_USERNAME:garagebid}
    password: ${DB_PASSWORD:garagebid}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        default_schema: auction
  flyway:
    schemas: auction
    default-schema: auction
  mvc:
    problemdetails:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info