server:
  port: 8082

spring:
  application:
    name: auction

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5434/auction}
    username: ${DB_USERNAME:garagebid}
    password: ${DB_PASSWORD:garagebid}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

  mvc:
    problemdetails:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info