INSERT INTO cars (id, make, model, model_year, mileage_km, price_usd, color, condition, description) VALUES
                                                                                                         (gen_random_uuid(), 'Ferrari',      '488 Pista',       2019, 8400,   395000.00,  'Rosso Corsa',    'EXCELLENT', 'Track-focused V8, tek sahip.'),
                                                                                                         (gen_random_uuid(), 'Lamborghini',  'Huracan STO',     2022, 3100,   410000.00,  'Blu Laufey',     'MINT',      'Street-legal race car, full PPF.'),
                                                                                                         (gen_random_uuid(), 'McLaren',      '720S',            2018, 15200,  245000.00,  'Papaya Spark',   'GOOD',      'Servis geçmişi tam.'),
                                                                                                         (gen_random_uuid(), 'Porsche',      '911 GT3 RS',      2023, 1900,   295000.00,  'GT Silver',      'MINT',      'Weissach paketi.'),
                                                                                                         (gen_random_uuid(), 'Aston Martin', 'DBS Superleggera',2020, 11800,  265000.00,  'Onyx Black',     'EXCELLENT', '5.2L twin-turbo V12.'),
                                                                                                         (gen_random_uuid(), 'Ferrari',      'SF90 Stradale',   2021, 4600,   565000.00,  'Giallo Modena',  'EXCELLENT', 'Assetto Fiorano pack.'),
                                                                                                         (gen_random_uuid(), 'Bugatti',      'Chiron',          2019, 2200,   3200000.00, 'French Racing',  'MINT',      'W16 quad-turbo.'),
                                                                                                         (gen_random_uuid(), 'Pagani',       'Huayra',          2016, 5400,   3100000.00, 'Exposed Carbon', 'EXCELLENT', 'El yapımı hypercar.'),
                                                                                                         (gen_random_uuid(), 'Lamborghini',  'Aventador SVJ',   2019, 6900,   520000.00,  'Verde Alceo',    'GOOD',      'ALA aero sistemi.'),
                                                                                                         (gen_random_uuid(), 'Koenigsegg',   'Regera',          2020, 1500,   2400000.00, 'Ghost White',    'MINT',      '1500 hp hybrid.'),
                                                                                                         (gen_random_uuid(), 'Mercedes-AMG', 'GT Black Series', 2021, 7300,   385000.00,  'Magno Grey',     'EXCELLENT', 'Flat-plane V8.'),
                                                                                                         (gen_random_uuid(), 'Ford',         'GT',              2018, 9800,   1050000.00, 'Liquid Blue',    'GOOD',      'Carbon monocoque.');